##Create an overlaying Grid layer_final_v_3=name
##NUMBER_SIZEOFGRIDCELLS=number20.0
##VECTORLAYER_LANDWATER=vector
##STRING_MAXAREA=string800
##NUMBER_MINAREAOFELEMENTS=number100.0
##STRING_MINAREAOFELEMENTS=string100
##EXTENT_MAPEXTENT=extent
##mapgrid=output vector
outputs_QGISDISSOLVE_1=processing.runalg('qgis:dissolve', VECTORLAYER_LANDWATER,True,None,None)
outputs_QGISCREATEGRID_1=processing.runalg('qgis:creategrid', 1,EXTENT_MAPEXTENT,NUMBER_SIZEOFGRIDCELLS,NUMBER_SIZEOFGRIDCELLS,'EPSG:4326',None)
outputs_QGISMULTIPARTTOSINGLEPARTS_1=processing.runalg('qgis:multiparttosingleparts', outputs_QGISDISSOLVE_1['OUTPUT'],None)
outputs_QGISFIELDCALCULATOR_1=processing.runalg('qgis:fieldcalculator', outputs_QGISMULTIPARTTOSINGLEPARTS_1['OUTPUT'],'area',0,10.0,3.0,True,'$area',None)
outputs_QGISEXTRACTBYATTRIBUTE_1=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_1['OUTPUT_LAYER'],'area',4,STRING_MINAREAOFELEMENTS,None)
outputs_QGISDIFFERENCE_3=processing.runalg('qgis:difference', VECTORLAYER_LANDWATER,outputs_QGISEXTRACTBYATTRIBUTE_1['OUTPUT'],True,None)
outputs_QGISMULTIPARTTOSINGLEPARTS_4=processing.runalg('qgis:multiparttosingleparts', outputs_QGISDIFFERENCE_3['OUTPUT'],None)
outputs_QGISREMOVENULLGEOMETRIES_1=processing.runalg('qgis:removenullgeometries', outputs_QGISMULTIPARTTOSINGLEPARTS_4['OUTPUT'],None)
outputs_QGISDIFFERENCE_2=processing.runalg('qgis:difference', outputs_QGISCREATEGRID_1['OUTPUT'],outputs_QGISREMOVENULLGEOMETRIES_1['OUTPUT_LAYER'],True,None)
outputs_SCRIPTSLIVERELIMINATOR_3=processing.runalg('script:slivereliminator', outputs_QGISREMOVENULLGEOMETRIES_1['OUTPUT_LAYER'],NUMBER_MINAREAOFELEMENTS,None)
outputs_QGISREMOVENULLGEOMETRIES_2=processing.runalg('qgis:removenullgeometries', outputs_QGISDIFFERENCE_2['OUTPUT'],None)
outputs_QGISMULTIPARTTOSINGLEPARTS_2=processing.runalg('qgis:multiparttosingleparts', outputs_QGISREMOVENULLGEOMETRIES_2['OUTPUT_LAYER'],None)
outputs_QGISFIELDCALCULATOR_2=processing.runalg('qgis:fieldcalculator', outputs_QGISMULTIPARTTOSINGLEPARTS_2['OUTPUT'],'REGION',2,10.0,3.0,True,''Ocean'',None)
outputs_QGISFIELDCALCULATOR_4=processing.runalg('qgis:fieldcalculator', outputs_SCRIPTSLIVERELIMINATOR_3['land'],'area',0,10.0,3.0,True,'$area',None)
outputs_SCRIPTSLIVERELIMINATOR_1=processing.runalg('script:slivereliminator', outputs_QGISFIELDCALCULATOR_2['OUTPUT_LAYER'],NUMBER_MINAREAOFELEMENTS,None)
outputs_QGISEXTRACTBYATTRIBUTE_3=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_4['OUTPUT_LAYER'],'area',3,STRING_MAXAREA,None)
outputs_QGISEXTRACTBYATTRIBUTE_2=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_4['OUTPUT_LAYER'],'area',4,STRING_MAXAREA,None)
outputs_QGISINTERSECTION_1=processing.runalg('qgis:intersection', outputs_QGISEXTRACTBYATTRIBUTE_3['OUTPUT'],outputs_QGISCREATEGRID_1['OUTPUT'],True,None)
outputs_QGISMULTIPARTTOSINGLEPARTS_3=processing.runalg('qgis:multiparttosingleparts', outputs_QGISINTERSECTION_1['OUTPUT'],None)
outputs_SCRIPTSLIVERELIMINATOR_2=processing.runalg('script:slivereliminator', outputs_QGISMULTIPARTTOSINGLEPARTS_3['OUTPUT'],NUMBER_MINAREAOFELEMENTS,None)
outputs_QGISSYMMETRICALDIFFERENCE_1=processing.runalg('qgis:symmetricaldifference', outputs_SCRIPTSLIVERELIMINATOR_2['land'],outputs_QGISEXTRACTBYATTRIBUTE_2['OUTPUT'],None)
outputs_QGISSYMMETRICALDIFFERENCE_2=processing.runalg('qgis:symmetricaldifference', outputs_QGISSYMMETRICALDIFFERENCE_1['OUTPUT'],outputs_SCRIPTSLIVERELIMINATOR_1['land'],mapgrid)